#ifndef CONSTANTS_H
#define CONSTANTS_H

#define DEFAULT_ARGC_NUM 2
#define SOURCE_TREE_FULL_PATH_ARGC_IDX 1
#define TARGET_TREE_FULL_PATH_ARGC_IDX 2

#define ERROR_BUFSIZE 1025
#define SEPARATOR "/"
#define INITIAL_VALUE ""
#define CURRENT_DIR "."
#define PREVIOUS_DIR ".."
#define WAIT_SEC_FOR_FD 1
#define WAIT_SEC_FOR_RESOURCES 1
#define DEFAULT_FOLDER_MODE 0700

#define NO_MODE 0

#define SUCCESS 0
#define ERROR (-1)

#define END_OF_FILE 0

#endif
