#ifndef CONSTANTS_H
#define CONSTANTS_H

#define DEFAULT_ARGC_NUM 2
#define SOURCE_TREE_FULL_PATH_ARGC_IDX 1
#define TARGET_TREE_FULL_PATH_ARGC_IDX 2

#define BUFSIZE 4097
#define ERROR_BUFSIZE 1025
#define WAIT_SEC_FOR_FD 1
#define WAIT_SEC_FOR_THREAD_RESOURCES 5

#define SUCCESS 0
#define ERROR (-1)

#endif
